flowchart TD;
	n1("component");
	n3("subsystem");
	n1-->|"in1"|n3;
	n1-->|"in2"|n3;
	n3-->|"out2"|n1;
subgraph subsystem [subsystem];
	n4("in1");
	n5("in2");
	n6("out2");
	n7("subcomponent 1");
	n8("subcomponent 2");
	n10("subsystem2");
	n4-->n7;
	n7-->n8;
	n7-->|"in3"|n10;
	n8-->n6;
	n10-->|"out3"|n8;
end;
